#include "dir_cache.h"

#include <iostream>

int main()
{
    //this file is generated by gen_dir_list.py, see readme for more help.
    const char * filename = "ora.dir"; 

    ApkDirectoryCache cache;
    if (!cache.load(filename))
    {
        std::cout << "error: can't open file " << filename << std::endl;
        return 0;
    }

    std::cout << "total bytes: " << cache.bytes()  << " bytes" << std::endl;

    cache.getRoot()->print("");

    const char * testfile = "Debug/dircache.exe";

    std::cout << "test file: " << testfile << std::endl;
    std::cout << "is exist: " << cache.exist(testfile) << std::endl;
    std::cout << "is  file: " << cache.isfile(testfile) << std::endl;
    std::cout << "is   dir: " << cache.isdir(testfile) << std::endl;

    return 0;
}
